(display '())
(newline)
(display (quote (1 #t 3)))
(newline)
(display '(1 2 . 3))
(newline)
(display (quote ()))
(newline)
(display (cons 4 (cons '("Hello" 3) '(1 2 3))))
(newline)
(display (cons 4 (cons '("Hello" 3) '(1 2 . 3))))
(newline)
