(display 1)
(newline)
(display #t)
(newline)
(display '(1 2 3))
(newline)
(display ((lambda (x) x) 5))
(newline)
(display ((lambda x x) 5))
(newline)
(display '(3 4 . "Hello"))
(newline)
(display '(3 4 . #\n))
(newline)
